chad:
  botToken: ""
  enableNotificationRoles: true
  notificationChannelId: 701824005954600960
  statusChannelId: 701102820409212968
  playingMessage: "with Kotlin"
  commandChar: ','
  disableSpoilers: true
  enableLinkPreview: true
  irc:
    name: "OREChad"
    server: "irc.esper.net"
    channel: "#orebotspam"
    password: "lolno"
  notifications:
    - role: "Survival"
      emoji: "🇸"
      name: "🇸urvival"
      description: "Survival updates"
    - role: "Modded"
      emoji: "🇲"
      name: "🇲odded"
      description: "Modded updates"
    - role: "Updates"
      emoji: "🇺"
      name: "🇺pdates"
      description: "Network updates"
  authorizedIrcRoles:
    - "op"
  authorizedDiscordRoles:
    - "Staff"
  insults:
    - "once in the 4th grade %USER% got a 2% on their math quiz so everyone called them milk for the rest of the year"
    - "%USER% may look like an idiot and talk like an idiot but don't let that fool you. %USER% really is an idiot."
    - "%USER%, you warthog-faced buffoon."
    - "%USER%, I fart in your general direction. Your mother was a hamster and your father smelt of elderberries."
    - "%USER% has no enemies, but is intensely disliked by their friends."
    - "%USER% is a cockalorum."
    - "%USER% ........ pillock."
    - "%USER% is more disappointing than an unsalted pretzel."
    - "%USER% is the reason God created the middle finger."
    - "I’ll never forget the first time I met %USER%. But I’ll keep trying."
    - "Hold still. I’m trying to imagine %USER% with a personality."
  commonCommands:
    ping: "pong"
  discordCommands:
    archive: "<https://archive.openredstone.org/>"
    invite: "<https://openredstone.org/discord>"
    owner: "<https://openredstone.org/owner/>"
    rules: "<https://openredstone.org/rules/>"
    schems: "<https://schems.openredstone.org/>"
    list: "Check <#701102820409212968> for current network status."
  ircCommands:
    archive: "https://archive.openredstone.org/"
    invite: "https://openredstone.org/discord"
    owner: "https://openredstone.org/owner/"
    rules: "https://openredstone.org/rules/"
    schems: "https://schems.openredstone.org/"
