chad:
  botToken: ""
  notificationChannelId: 701813343530254346
  statusChannelId: 701115144842903615
  playingMessage: "with Kotlin"
  commandChar: ','
  disableSpoilers: true
  irc:
    name: "OREChad"
    server: "irc.esper.net"
    channel: "#orebotspam"
    password: "lolno"
  notifications:
    - role: "Survival"
      emoji: "🇸"
      name: "🇸urvival"
      description: "Survival updates"
    - role: "Modded"
      emoji: "🇲"
      name: "🇲odded"
      description: "Modded updates"
    - role: "Updates"
      emoji: "🇺"
      name: "🇺pdates"
      description: "Network updates"
  insults:
    - "once in the 4th grade %USER% got a 2% on their math quiz so everyone called them milk for the rest of the year"
  discordCommands:
    archive: "<https://archive.openredstone.org/>"
    invite: "<https://openredstone.org/discord>"
    schems: "<https://schems.openredstone.org/>"
    llist: "Check <#701115144842903615> for current network status."
  ircCommands:
    archive: "https://archive.openredstone.org/"
    invite: "https://openredstone.org/discord"
    schems: "https://schems.openredstone.org/"
