chad:
  botToken: ""
  notificationChannelId: 701813343530254346
  statusChannelId: 701115144842903615
  playingMessage: "with Kotlin"
  commandChar: ','
  disableSpoilers: true
  irc:
    name: "OREChad"
    server: "irc.esper.net"
    channel: "#orebotspam"
    password: "lolno"
  notifications:
    - role: "Survival"
      emoji: "🇸"
      name: "🇸urvival"
      description: "Survival updates"
    - role: "Modded"
      emoji: "🇲"
      name: "🇲odded"
      description: "Modded updates"
    - role: "Updates"
      emoji: "🇺"
      name: "🇺pdates"
      description: "Network updates"
  discordCommands:
    - name: "archive"
      reply: "<https://archive.openredstone.org/>"
    - name: "invite"
      reply: "<https://openredstone.org/discord>"
    - name: "schems"
      reply: "<https://schems.openredstone.org/>"
    - name: "llist"
      reply: "Check <#701115144842903615> for current network status."
  ircCommands:
    - name: "archive"
      reply: "https://archive.openredstone.org/"
    - name: "invite"
      reply: "https://openredstone.org/discord"
    - name: "schems"
      reply: "https://schems.openredstone.org/"
